# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'getLocal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for getLocal
  pod 'Firebase'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
    pod 'Firebase/Core'
    pod 'Firebase/Storage'
	pod 'FacebookCore'
	pod 'FacebookLogin'
	pod 'SwiftOverlays', '~> 4.0.0'
end
